toc: false
number-sections: false
lang: de

format:
  pdf:
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{fancyhdr}
        \fancypagestyle{firstpage}{
          \fancyhf{}
          \fancyhead[C]{\includegraphics[width=2in]{logo.png}}
          \renewcommand{\headrulewidth}{0pt}
        }
        \AtBeginDocument{\thispagestyle{firstpage}}
