project:
  type: book
  output-dir: book
  
lang: de

book:
  title: "Digitalisierung und Programmierung"
  subtitle: "Vorlesungsskript"
  author: "Prof. Dr. Nicolas Meseth"
  date: today
  date-format: long
  output-file: "book_digitalisierung_und_programmierung"
  search: true
  downloads: [pdf]


  chapters:
    - index.qmd
    - lifi-project.qmd
    - lifi-project-hardware-software.qmd
    - part: problems.qmd
      chapters:
        - problem-solving.qmd
        - algorithms.qmd
    - part: information-representation.qmd
      chapters:
        - information.qmd
        - bits.qmd
        - code-systems.qmd
        - data-structures.qmd
    - part: information-processing.qmd
      chapters:
        - analog-vs-digital.qmd
        - storage.qmd
        - logic-and-arithmetic.qmd
        - computer.qmd
    - part: information-sharing.qmd
      chapters:
        - signals.qmd
        - protocols.qmd
        - encryption.qmd
        - compression.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  html:
    theme: cosmo
    highlight: pygments
    toc-depth: 2
    number-sections: true