---
title: "Willkommen in Python"
author: "Prof. Dr. Nicolas Meseth"
format: pdf
toc: true
number-sections: false
code-line-numbers: true
subtitle: "Tutorials zur Programmierung"
---

## Unser erstes Programm

Unser erstes Programm könnte so aussehen:

```python
# Ask the user for their name
name = input("What's your name? ")

# Greet the user
print(f"Hello {name}")
```
Ein **Programm** besteht aus einer Reihe von Anweisungen, die von einem Computer ausgeführt werden. Ein Programm wird als reiner Text geschrieben, und üblicherweise verwenden wir für jede neue Anweisung eine separate Zeile. Um ein Programm zu schreiben, benötigen wir lediglich einen einfachen Texteditor. Allerdings bevorzugen wir eine vollständige Entwicklungsumgebung wie [Visual Studio Code](https://code.visualstudio.com/download), da sie viele hilfreiche Funktionen wie Syntaxhervorhebung, automatische Vervollständigung und Debugging-Tools bietet, die das Programmieren erleichtern.

Wenn ein Computer ein Programm ausführt, geht er Zeile für Zeile durch das Programm und führt aus, was jede Zeile - oder **Anweisung** - ihm vorgibt. Im Beispiel oben wird zuerst die Zeile 

```python
name = input("What's your name? ")
```
ausgeführt. Diese Zeile nutzt die Funktion `input()`, um eine Eingabe vom Benutzer abzufragen. Das Ergebnis wird in einer Variable namens `name` gespeichert. Anschließend geht der Computer zur nächsten Zeile, wo er die Anweisung

```python
print(f"Hello {name}")
```
vorfindet. `print()` ist eine Funktion, die eine Nachricht auf der Konsole ausgibt. 

Vielleicht fragst du dich, was es mit den beiden Zeilen auf sich hat, die mit einem #-Symbol beginnen?

```python
# Ask the user for their name
# Greet the user
```
Diese Zeilen sind **Kommentare **und gehören nicht zum eigentlichen Programm. Der Computer überspringt sie – sie dienen ausschließlich uns Menschen als Hilfestellung. Ein gut platzierter Kommentar kann das Verständnis des Codes erheblich erleichtern.

Im Beispiel oben werden die Befehle Zeile für Zeile ausgeführt – das ist der Normalfall in einem Programm. Es gibt jedoch spezielle Anweisungen wie **Schleifen**, **Kontrollstrukturen** und **Funktionen**, die den Computer veranlassen, Befehle in einer anderen Reihenfolge auszuführen. Mit diesen Anweisungen kann der Computer bestimmte Aktionen wiederholen oder Codezeilen überspringen. Keine Sorge, wenn dir diese Konzepte noch nicht ganz klar sind – wir werden sie bald näher kennenlernen.

## Ein Programm ausführen

Um ein Python-Programm auszuführen, benötigen wir einen Python-Interpreter – das Programm, das unseren Python-Code Zeile für Zeile liest und ausführt. In Visual Studio Code können wir ein Python-Programm einfach mit einem Klick auf den „Play"-Button oder durch Drücken der Taste F5 starten. Ich persönlich bevorzuge jedoch den Weg über die Kommandozeile (oder Terminal), da wir so die volle Kontrolle über die Ausführung unseres Programms haben. Ein weiterer Vorteil: Wir lernen dabei wichtige Kommandozeilenbefehle kennen, die in der Softwareentwicklung unverzichtbar sind. Mach dich also mit dem Terminal vertraut.

Öffne am besten direkt ein Terminal in Visual Studio Code. Das erreichst du im Menü unter "Terminal" → "New Terminal”. Achte darauf, dass es sich um ein Command Prompt (cmd) handelt, wenn du mit einem Windows-System arbeitest.

```bash
python my_first_program.py
```


