---
title: "Programmieren mit Python: Funktionen"
subtitle: "Digitalisierung und Programmierung"
lang: de
---

### Übungen

1.  Warum ist es nicht sinnvoll, hinter einer `return`-Anweisung innerhalb einer Funktion noch weitere Anweisungen zu schreiben?

2.  Erläutere die Funktionsweise eine Format-Strings in Python? was passiert mit den Platzhaltern, wenn wir das "f" als Prefix weglassen?

3.  Schreibe eine Funktion, die prüft, ob eine Zahl größer als die andere ist. Die Funktion soll zwei Parameter entgegennehmen und `True` zurückgeben, wenn die erste Zahl größer ist als die zweite, andernfalls `False`.

4. Schreibe ein Programm für das folgende Problem: Der Benutzer wird beim Start aufgefordert, einen beliebigen Text bestehend aus Buchstaben und Zahlen einzugeben. Dein Programm soll den Text in Morse Code umwandeln und als Ton ausgeben. Verwende dazu die Funktion `Beep(frequency, duration)` aus dem Modul `winsound`. Die Funktion `Beep` erwartet zwei Parameter: die Frequenz des Tons in Hertz und die Dauer des Tons in Millisekunden. Wähle eine geeignete Frequenz für die Töne und schlage die Dauer der Töne für Dots, Dashes und Pausen im Internet nach. Gehe nach dem in der Vorlesung eingeführten Problemlösungsschema vor.
