---
title: "Übungen zu: 2. Information"
subtitle: "Digitalisierung und Programmierung"
lang: de
---

### Übungen

1.  Was ist der Unterschied zwischen der Unsicherheit $H$ und Information $I$? Was haben beide Größen gemeinsam?

2.  Erläutere mit eigenen Worten, warum Ja/Nein-Fragen, die den Raum der Möglichkeiten jeweils halbieren, am effizientesten sind.

3. Ihr sollt einen Buchstaben aus dem Alphabet erraten und dürft so viele Ja/Nein-Fragen stellen, wie ihr wollt. Welche Fragen stellt ihr?

4.  Warum ist das Bit die kleinste mögliche Informationseinheit?

5.  Warum verwenden wir bei der Berechnung des Speicherbedarfs einer Nachricht die Formel $H = \lceil log_2(S) \rceil \times n$ und nicht $H = log_2(S) \times n$?

6. Wie viele Bits benötigen wir, um die folgenden Anzahlen möglicher Nachrichten zu repräsentieren?

    a.  10
    
    b.  64
    
    c.  128
    
    d.  1000
    
    e.  1024
    
    f.  16777216
    

7.  Berechnet den Bedarf an Bits, um die folgenden Nachrichten zu repräsentieren:

    a.  Ein deutsches Autonummernschild

    b.  Eine Doppelkopfhand

    c.  Die Lottozahlen
    
    d.  Eine zehnstellige Telefonnummer
    
    e.  Ein acht Zeichen langes Passwort, das nur Großbuchstaben, Kleinbuchstaben und Zahlen enthält.
    
    f.  Eine IPv4-Adresse.

8.  Wie viel Information steckt theoretisch in der menschlischen DNA? Warum bräuchten wir in der Praxis deutlich weniger Speicherplatz, um die menschliche DNA zu speichern?
