### Reflektionsfragen

1.  Welche Funktionen kennst du, die zum Funktionsumfang von Python gehören? Schlag in der [Dokumentation](https://docs.python.org/3/) nach und nenne mindestens 5 Funktionen und erläutere ihren Zweck!

2.  Erläutere die Begriffe *Parameter* und *Rückgabewert* im Zusammenhang mit Funktionen in der Programmierung und nenne jeweils ein Beispiel!

3.  Wozu können Kommentare in einem Programm nützlich sein?

4.  Beschreibt die Konventionen für die Benennung von Variablen oder Funktionen in Python! Warum ist es sinnvoll, Konventionen zu haben und einzuhalten?

5.  Was versteht man unter dem Begriff *bug* in der Programmierung? Welche Arten kennst du?

6.  Beschreibe mit eigenen Worten, was unter einer *Variable* zu verstehen ist! Was ist eine Variable aus technischer Sicht?

### Programmieraufgaben


1.  Schreibe ein Programm, das den Benutzer um die Eingabe seines Namens bittet und ihn anschließend unter Nennung seines Namens begrüßt! Formuliere dein Programm zunächst als Pseudocode und schreibe die Schritte als Kommentare in dein Programm!

2.  Recherchiere, wie wir den Benutzer um die Eingabe von Zahlen bitten können und wie wir diese Zahlen in Python verarbeiten können! Schreibe ein Programm, das den Benutzer um die Eingabe von zwei Zahlen bittet und anschließend die Summe der beiden Zahlen ausgibt! Welche Art von Fehler kann dabei auftreten?

